# Generated by Django 4.0.10 on 2023-08-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='facebook',
            field=models.CharField(blank=True, default='input you Facebook link here.', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='github',
            field=models.CharField(blank=True, default='input you Github link here.', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='googleplus',
            field=models.CharField(blank=True, default='input you Google+ link here.', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram',
            field=models.CharField(blank=True, default='input you Instagram link here.', max_length=1000, null=True),
        ),
    ]
