# Generated by Django 4.0.10 on 2023-08-12 05:42

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='default', max_length=100)),
                ('image', models.ImageField(default='default.jpg', upload_to='hospital_abt_images')),
            ],
        ),
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='default', max_length=100)),
                ('body', models.TextField(default='Please write the description here', max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='BaseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_img', models.ImageField(blank=True, default='default.png', null=True, upload_to='company_Logo')),
                ('logo_name', models.CharField(default='Chipped', max_length=100)),
                ('footer', models.CharField(default='Update Footer ', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContactSidebarCompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FrontPageCard1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Emergency Case', max_length=100)),
                ('body', models.CharField(default='default', max_length=200)),
                ('color', models.CharField(default='green', max_length=100)),
                ('iconInput', models.CharField(default='default', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FrontPageCard3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Clinic Timetable', max_length=100)),
                ('body', models.CharField(default='default', max_length=200)),
                ('color', models.CharField(default='green', max_length=100)),
                ('iconInput', models.CharField(default='default', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Welcome to Our Caring Hospital', max_length=100)),
                ('body', models.TextField(blank=True, default='At Our Caring Hospital, we are dedicated to providing exceptional medical care with compassion and expertise. Your health and well-being are our top priorities, and we take pride in offering a wide range of medical services to meet all your healthcare needs.', max_length=600, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TopFooterHeading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='default', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=100)),
                ('hours', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TopFooterContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='default', max_length=200)),
                ('url', models.CharField(blank=True, max_length=1000, null=True)),
                ('heading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_website.topfooterheading')),
            ],
        ),
    ]
