
# Generated by Django 4.0.10 on 2023-07-30 06:01

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='default', max_length=100)),
                ('body', models.TextField(default='desc', max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='BaseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_img', models.ImageField(default='default.jpg', upload_to='company_Logo')),
                ('logo_name', models.CharField(default='default', max_length=100)),
                ('footer', models.CharField(default='Update Footer ', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContactSidebarCompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='default', max_length=100)),
                ('body', models.TextField(default='desc', max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='main_page_service_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='default', max_length=100)),
                ('body', models.TextField(default='desc', max_length=600)),
                ('color', models.CharField(default='green', max_length=100)),
                ('image', models.ImageField(default='default_P.png', upload_to='main_page_service_details')),
            ],
        ),
    ]
