
# Generated by Django 4.0.10 on 2023-07-31 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopFooterContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='default', max_length=200)),
                ('url', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TopFooterHeading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='default', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='main_page_service_details',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=models.TextField(default='hpage_desc', max_length=600),
        ),
        migrations.AddField(
            model_name='topfootercontent',
            name='heading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_website.topfooterheading'),
        ),
    ]