
# Generated by Django 4.0.10 on 2023-07-31 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_website', '0002_topfootercontent_topfooterheading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='body',
            field=models.TextField(default='Please write the description here', max_length=600),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=models.TextField(default='At Our Caring Hospital, we are dedicated to providing exceptional medical care with compassion and expertise. Your health and well-being are our top priorities, and we take pride in offering a wide range of medical services to meet all your healthcare needs.', max_length=600),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='heading',
            field=models.CharField(default='Welcome to Our Caring Hospital', max_length=100),
        ),
    ]
