# Generated by Django 4.0.10 on 2023-08-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_website', '0003_socialmedialink'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageCard1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Emergency Case', max_length=100)),
                ('body', models.CharField(default='default', max_length=200)),
                ('color', models.CharField(default='green', max_length=100)),
                ('iconInput', models.CharField(default='default', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HomePageCard3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Clinic Timetable', max_length=100)),
                ('body', models.CharField(default='default', max_length=200)),
                ('color', models.CharField(default='green', max_length=100)),
                ('iconInput', models.CharField(default='default', max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='FrontPageCard1',
        ),
        migrations.DeleteModel(
            name='FrontPageCard3',
        ),
    ]
