# Generated by Django 4.0.10 on 2023-09-06 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_website', '0005_alter_aboutlist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topfootercontent',
            name='heading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_items', to='hospital_website.topfooterheading'),
        ),
    ]
