# Generated by Django 4.0.10 on 2023-08-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_website', '0006_aboutlist_frontpagecard1_frontpagecard3_workinghours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basedata',
            name='logo_img',
            field=models.ImageField(default='default.png', upload_to='company_Logo'),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='logo_name',
            field=models.CharField(default='Chipped', max_length=100),
        ),
    ]
