# Generated by Django 4.0.10 on 2023-09-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_website', '0006_alter_aboutlist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutlist',
            name='image',
            field=models.ImageField(upload_to='hospital_abt_images'),
        ),
    ]
