# Generated by Django 4.0.10 on 2023-09-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_website', '0006_alter_topfootercontent_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutlist',
            name='related_items',
            field=models.ManyToManyField(blank=True, to='hospital_website.aboutlist'),
        ),
    ]
