# Generated by Django 4.0.10 on 2023-09-10 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_website', '0007_aboutlist_related_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutlist',
            name='related_items',
        ),
    ]
