# Generated by Django 4.0.10 on 2023-10-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_website', '0009_alter_socialmedialink_facebook_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsidebarcompanyinfo',
            name='whatsapp',
            field=models.URLField(default='https://wa.me/enternumber'),
        ),
    ]
