# Generated by Django 4.0.10 on 2023-09-30 05:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField()),
                ('day', models.DateField()),
                ('hour', models.PositiveSmallIntegerField()),
                ('minute', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
