# Generated by Django 4.0.10 on 2023-09-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors_counter', '0003_visit_visit_count_alter_visit_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='ip_address',
            field=models.GenericIPAddressField(),
        ),
    ]
