# Generated by Django 4.0.10 on 2023-09-30 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors_counter', '0004_alter_visit_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='visit_count',
        ),
    ]
