# Generated by Django 4.0.10 on 2023-09-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors_counter', '0005_remove_visit_visit_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='visit_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
