# Generated by Django 4.0.10 on 2023-09-30 09:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('visitors_counter', '0006_visit_visit_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='last_visit',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
