# Generated by Django 4.0.10 on 2023-10-14 18:28

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='Dental Services Cat-', max_length=200)),
                ('cat_description', models.TextField(default='CaT- Lorem ipsum dolor sit amet, consectetur adipisicingpra esentium eveniet eum libero assumenda.')),
                ('iconInput', models.CharField(default='<i class="fa-icon fa-solid fa-truck-medical"></i>', max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceOffered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(default='Dental Services', max_length=100)),
                ('description', models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipisicingpra esentium eveniet eum libero assumenda.')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_services.servicecategory')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_services.serviceoffered')),
            ],
        ),
    ]
