# Generated by Django 4.0.10 on 2023-09-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_services', '0002_servicecategory_serviceoffered'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceoffered',
            name='iconInput',
            field=models.CharField(default='default', max_length=200),
        ),
    ]
