# Generated by Django 4.0.10 on 2023-09-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_services', '0004_alter_servicecategory_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceoffered',
            name='iconInput',
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='iconInput',
            field=models.CharField(default='<i class="fa-icon fa-solid fa-truck-medical"></i>', max_length=200),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='category_name',
            field=models.CharField(default='Dental Services', max_length=100),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='description',
            field=models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipisicingpra esentium eveniet eum libero assumenda.'),
        ),
    ]
