# Generated by Django 4.0.10 on 2023-09-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_services', '0005_remove_serviceoffered_iconinput_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecategory',
            name='category_name',
            field=models.CharField(default='Dental Services', max_length=200),
        ),
        migrations.AlterField(
            model_name='serviceoffered',
            name='description',
            field=models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipisicingpra esentium eveniet eum libero assumenda.'),
        ),
        migrations.AlterField(
            model_name='serviceoffered',
            name='service_name',
            field=models.CharField(default='Dental Services', max_length=100),
        ),
    ]
