# Generated by Django 4.0.10 on 2023-09-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_services', '0006_alter_servicecategory_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecategory',
            name='description',
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='cat_description',
            field=models.TextField(default='CaT- Lorem ipsum dolor sit amet, consectetur adipisicingpra esentium eveniet eum libero assumenda.'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='category_name',
            field=models.CharField(default='Dental Services Cat-', max_length=200),
        ),
    ]
