# Generated by Django 4.0.10 on 2023-09-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_services', '0007_remove_servicecategory_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceoffered',
            name='delete_identifier',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
