# Generated by Django 4.0.10 on 2023-09-24 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_services', '0008_serviceoffered_delete_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceoffered',
            name='delete_identifier',
        ),
    ]
