
# Generated by Django 4.0.10 on 2023-08-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='category-default.jpg', null=True, upload_to='category_images'),
        ),
    ]
